version: '3.9'

services:
  nocap-fastapi:
    build: .
    image:  ${REGISTRY_HOST}/${NAMESPACE}/${REPO}:${TAG}
    container_name: fastapi-container
    ports:
      - "80:8000"
      - "8000:8000"
    restart: unless-stopped
