apiVersion: apps/v1
kind: Deployment
metadata:
  name: nocap-fastapi
  namespace: nocap
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nocap-fastapi
  template:
    metadata:
      labels:
        app: nocap-fastapi
    spec:
      imagePullSecrets:
        - name: ncr-cred
      containers:
        - name: nocap-fastapi
          image: no-cap.kr.ncr.ntruss.com/nocap-fastapi:latest
          ports:
            - containerPort: 80
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENAI_API_KEY
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
