apiVersion: apps/v1
kind: Deployment
metadata:
  name: nocap-fastapi
  namespace: nocap
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  progressDeadlineSeconds: 1800
  selector:
    matchLabels:
      app: nocap-fastapi
  template:
    metadata:
      labels:
        app: nocap-fastapi
    spec:
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
        - name: ncr-cred
      containers:
        - name: nocap-fastapi
          image: no-cap.kr.ncr.ntruss.com/nocap-fastapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENAI_API_KEY
            - name: OMP_NUM_THREADS
              value: "1"
            - name: MKL_NUM_THREADS
              value: "1"
            - name: TOKENIZERS_PARALLELISM
              value: "false"
            - name: PYTHONUNBUFFERED
              value: "1"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
              ephemeral-storage: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
              ephemeral-storage: "512Mi"
          startupProbe:
            tcpSocket:
              port: 80
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 120
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 25
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 120
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 3
