apiVersion: apps/v1
kind: Deployment
metadata:
  name: nocap-fastapi
  namespace: nocap
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: nocap-fastapi
  template:
    metadata:
      labels:
        app: nocap-fastapi
    spec:
      imagePullSecrets:
        - name: ncr-cred
      containers:
        - name: nocap-fastapi
          image: no-cap.kr.ncr.ntruss.com/nocap-fastapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENAI_API_KEY
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
              ephemeral-storage: "512Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
              ephemeral-storage: "512Mi"
          startupProbe:
            tcpSocket: { port: 80 }
            failureThreshold: 30
            periodSeconds: 3
          readinessProbe:
            tcpSocket: { port: 80 }
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            tcpSocket: { port: 80 }
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 3
