apiVersion: apps/v1
kind: Deployment
metadata:
  name: nocap-fastapi
  namespace: nocap
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  progressDeadlineSeconds: 1800
  selector:
    matchLabels:
      app: nocap-fastapi
  template:
    metadata:
      labels:
        app: nocap-fastapi
    spec:
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
        - name: ncr-cred
      securityContext:
        fsGroup: 0
      containers:
        - name: nocap-fastapi
          image: no-cap.kr.ncr.ntruss.com/nocap-fastapi:latest
          imagePullPolicy: Always
          command: ["python","-m","uvicorn"]
          args: ["app.main:app","--host","0.0.0.0","--port","8000","--workers","1"]
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENAI_API_KEY
            - name: OMP_NUM_THREADS
              value: "1"
            - name: MKL_NUM_THREADS
              value: "1"
            - name: TOKENIZERS_PARALLELISM
              value: "false"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: TRANSFORMERS_CACHE
              value: /root/.cache/huggingface
            - name: HF_HOME
              value: /root/.cache/huggingface
            - name: HUGGINGFACE_HUB_CACHE
              value: /root/.cache/huggingface
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
              ephemeral-storage: "256Mi"
            limits:
              cpu: "500m"
              memory: "2Gi"
              ephemeral-storage: "512Mi"
          volumeMounts:
            - name: hf-models
              mountPath: /root/.cache/huggingface
          startupProbe:
            tcpSocket:
              port: 8000
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 120
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 60
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: hf-models
          persistentVolumeClaim:
            claimName: huggingface-pvc
