apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huggingface-pvc
  namespace: nocap
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  volumeName: huggingface-pv
