apiVersion: v1
kind: PersistentVolume
metadata:
  name: huggingface-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 169.254.82.16
    path: /n3067145_contest20
  mountOptions:
    - nfsvers=4.1
