apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nocap-model-pvc
  namespace: nocap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: nocap-model-pvc
  storageClassName: nks-block-storage
