name: NOCAP-FASTAPI CI/CD
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE: ${{ secrets.NCR_REGISTRY }}/${{ secrets.NCR_REPO_FASTAPI }}
      NAMESPACE: nocap
      DEPLOYMENT: nocap-fastapi
    steps:
      - uses: actions/checkout@v4

      - name: Docker login (NCR)
        run: |
          echo "${{ secrets.NCR_PASSWORD }}" | docker login \
            ${{ secrets.NCR_REGISTRY }} \
            -u "${{ secrets.NCR_USERNAME }}" --password-stdin

      - name: Build & push FastAPI image
        run: |
          set -euxo pipefail
          docker build -t $IMAGE_FASTAPI:latest .
          docker push $IMAGE_FASTAPI:latest

      - name: Print pushed image tags
        run: |
          echo "✅ Pushed: $IMAGE_FASTAPI:latest"