name: nocap-FastAPI CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          if [ ! -d "nocap-FastAPI" ]; then
          git clone https://github.com/kpaas-nocap/nocap-FastAPI.git
          fi
          cd nocap-FastAPI
          git fetch --all
          git reset --hard origin/main
          docker-compose down
          docker-compose rm -f
          docker-compose up -d --build